# Generated by Django 4.0 on 2024-10-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerinfo',
            name='owner_photo',
        ),
    ]
