# Generated by Django 4.0 on 2024-08-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='owners/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_info', to='App_Auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('mailing_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('logo_picture', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to='App_Auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year_in_operation', models.PositiveIntegerField()),
                ('ownership_structure', models.CharField(max_length=255)),
                ('trade_license_no', models.CharField(max_length=255)),
                ('business_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='App_Auth.businessinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('representative_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('business_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='App_Auth.businessinfo')),
            ],
        ),
    ]
