# Generated by Django 4.0 on 2024-08-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0003_alter_branchinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchinfo',
            name='business_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='App_Auth.businessinfo'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='business_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='App_Auth.businessinfo'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to='App_Auth.user'),
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_info', to='App_Auth.user'),
        ),
    ]
