# Generated by Django 4.0 on 2024-08-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Sqi', '0002_delete_branch_rename_ord_question_order_and_more'),
        ('App_Auth', '0004_alter_branchinfo_business_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='industry',
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='industry_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='App_Sqi.category'),
        ),
    ]
