# Generated by Django 4.0 on 2024-08-15 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0007_remove_businessdetails_ownership_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_start_date', models.DateField(auto_now_add=True)),
                ('sub_expire_date', models.DateField(blank=True, null=True)),
                ('subscription', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ceo_approval', models.BooleanField(default=False)),
                ('is_admin_user', models.BooleanField(default=False)),
                ('is_normal_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_profiles', to='App_Auth.branchinfo')),
                ('company_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_profiles', to='App_Auth.businessdetails')),
                ('company_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to='App_Auth.businessinfo')),
                ('owner_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profiles', to='App_Auth.ownerinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='App_Auth.user')),
            ],
        ),
    ]
