# Generated by Django 4.0 on 2024-08-15 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_profiles', to='App_Auth.branchinfo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_profiles', to='App_Auth.businessdetails'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='App_Auth.businessinfo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profiles', to='App_Auth.ownerinfo'),
        ),
    ]
