# Generated by Django 4.0 on 2024-08-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0009_alter_userprofile_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='branch',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branches',
            field=models.ManyToManyField(blank=True, null=True, related_name='branch_profiles', to='App_Auth.BranchInfo'),
        ),
    ]
