# Generated by Django 4.0 on 2024-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0010_remove_userprofile_branch_userprofile_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='branch_profiles', to='App_Auth.BranchInfo'),
        ),
    ]
