# Generated by Django 4.0 on 2024-08-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0014_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sub_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
